//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBuilding.Web.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BeaconSystemsEntities : DbContext
    {
        public BeaconSystemsEntities()
            : base("name=BeaconSystemsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Beacon> Beacons { get; set; }
        public virtual DbSet<Device> Devices { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<UserWorkstation> UserWorkstations { get; set; }
        public virtual DbSet<Workstation> Workstations { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
